# Generated by Django 4.2.3 on 2026-08-12 00:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freezer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreezerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('qty', models.IntegerField(default=1)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('date_added', models.DateField(default=datetime.date.today)),
                ('discard_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('freezer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.freezer')),
            ],
            options={
                'ordering': ['freezer', 'name'],
            },
        ),
    ]
