# Generated by Django 4.2.3 on 2026-08-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_freezer_freezeritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freezeritem',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
    ]
