# Generated by Django 4.2.3 on 2026-08-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_freezeritem_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='freezeritem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='freezeritems/'),
        ),
        migrations.AddField(
            model_name='freezeritem',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='freezeritems/thumbs/'),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AddField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='items/thumbs/'),
        ),
    ]
