# Generated by Django 4.2.3 on 2026-08-17 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_freezeritem_image_freezeritem_thumbnail_item_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreezerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('added', 'Added'), ('used', 'Used'), ('moved', 'Moved'), ('discarded', 'Thrown out')], max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('qty', models.IntegerField(default=1)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('freezer_name', models.CharField(max_length=50)),
                ('to_freezer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('occurred', models.DateTimeField(auto_now_add=True)),
                ('freezer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.freezer')),
                ('freezeritem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.freezeritem')),
            ],
            options={
                'ordering': ['-occurred', '-id'],
                'indexes': [models.Index(fields=['-occurred'], name='api_freezer_occurre_3e26e7_idx'), models.Index(fields=['name'], name='api_freezer_name_49708e_idx')],
            },
        ),
    ]
