# Develpoment stage for Vue.js
FROM node:lts-alpine AS vue-develop-stage

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Command to run the development server
CMD ["npm", "run", "serve"]
