services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    networks:
      - default
    restart: unless-stopped
    ports:
      - 8081:5173
    image: lenoreshop_frontend:development
    container_name: lenoreshop_frontend_dev
    volumes:
      - ./frontend:/app
    command: /bin/sh -c "npm run serve"
    env_file:
      - ./.env.dev
    environment:
      - NODE_ENV=development
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: /usr/src/app/start.dev.sh
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8001:8001
      - 8002:8002
    depends_on:
      - db
    networks:
      - default
    env_file:
      - ./.env.dev
    environment:
      - DEBUG=1
    image: lenoreshop_backend:development
    container_name: lenoreshop_backend_dev
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
    networks:
      - default
    container_name: lenoreshop_db_dev
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}

volumes:
  postgres_data:
  static_volume:
  media_volume:
