version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    networks:
      - default
    restart: unless-stopped
    ports:
      - 8081:8080
    image: lenoreshop_frontend:development
    container_name: lenoreshop_frontend_dev
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - TZ=America/New_York
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: /usr/src/app/start.dev.sh
    volumes:
      - ./backend:/usr/src/app
    environment:
      - DEBUG=1
      - TZ=America/New_York
    ports:
      - 8001:8001
    depends_on:
      - db
    networks:
      - default
    env_file:
      - ./.env.dev
    image: lenoreshop_backend:development
    container_name: lenoreshop_backend_dev
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
    networks:
      - default
    container_name: lenoreshop_db_dev
    environment:
      - TZ=America/New_York

volumes:
  postgres_data:
  static_volume:
  media_volume:
