services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: lenoreshop:production
    container_name: lenoreshop_app
    ports:
      - "${APP_PORT:-7000}:80"
    volumes:
      - lenoreshop_data:/home/app/web/data
      - lenoreshop_static:/home/app/web/staticfiles
      - lenoreshop_media:/home/app/web/mediafiles
    env_file:
      - ./.env
    restart: unless-stopped

volumes:
  lenoreshop_data:
  lenoreshop_static:
  lenoreshop_media:
