name: Versioning

on:
  workflow_run:
    workflows:
      - "Deploy MkDocs to GitHub Pages"
    types:
      - completed

jobs:
  versioning:
    runs-on: [self-hosted]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      
      - name: Set up GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y
          gh auth login --with-token < ${{ secrets.GH_PAT }}

      - name: Run Versioning Script
        run: |
          chmod +x scripts/versioning.sh
          ./scripts/versioning.sh
